version: 2.1

orbs:
   node: circleci/node@4.3.0

jobs:
  build_and_test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - node/install-packages:
         pkg-manager: yarn
      - run: 
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy Over SSH
          command: |
             echo "Starting deployment"
             ssh $SSH_USER@$SSH_HOST
             cp -Rf ~/project/* /www/wwwroot/nav.onestyle.top
             echo "Deployment finished"
           
workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
