version: 2.1

orbs:
   node: circleci/node@4.1.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
         pkg-manager: npm
      - run: 
          command: npm run serve
          name: Run tests
      - run: 
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - run: scp -r dist/ root@http://81.68.128.43:8888/:/www/wwwroot/nav.onestyle.top

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
