version: 2.1

orbs:
   node: circleci/node@4.6.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
         pkg-manager: yarn
      - run: 
          command: yarn serve
          name: Run tests
      - run: 
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    machine: true
    steps:
     - run:
            name: Deploy Over SSH
            command: |
             ssh -i Wty1098834475. root@81.68.128.43:8888 "<remote deploy command>"
             cp -Rf ~/project/* /www/wwwroot/nav.onestyle.top

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
