name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.16.0'

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build
      
    - name: rename
      run: mv ./build ./nav.onestyle.top
    
    - name: Copy package to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: ./nav.onestyle.top
        target: /www/wwwroot
